# Copyright (c) 2026, Loco-Manip HV1 Sim-to-Sim
# SPDX-License-Identifier: BSD-3-Clause
"""
Deploy a trained HV1 V3 (HiWET Stage-1) loco-manip policy in MuJoCo.

V3 differs from V2 in four ways the deploy runner must handle:

  1. Two extra scalar command obs: body_height_command, waist_alpha_command.
  2. Torso IMU obs (projected_gravity_torso, torso_ang_vel) — V2 deploy script
     omitted these; V3 policy was trained with them so they must be supplied.
  3. Observation history (length 5) — actor input is 605-d, not 121-d. Each
     obs term is buffered separately (CircularBuffer in Isaac), then per-term
     histories are flattened oldest→newest and concatenated in declaration
     order. This script mirrors that exactly.
  4. Action dim 28 (legs 12 + arms 14 + waist 2). Joint order from YAML.

The YAML is generated by:
  ./isaaclab.sh -p scripts/reinforcement_learning/rsl_rl/dump_mujoco_config.py \\
      --task Isaac-Tracking-LocoManipV3-HV1-Play-v0 --num_envs 1

Usage:
  python deploy_mujoco_hv1_v3.py \\
      --config <run_dir>/exported/mujoco_config.yaml \\
      --cmd_lin_x 0.3 --cmd_lin_y 0.0 --cmd_ang_z 0.0 \\
      --left_ee   0.30  0.26 0.24  1.0 0.0 0.0 0.0 \\
      --right_ee  0.30 -0.26 0.24  1.0 0.0 0.0 0.0 \\
      --cmd_body_height 0.90 \\
      --cmd_waist_alpha 1.0
"""

from __future__ import annotations

import argparse
import sys
import time
from collections import deque
from typing import Callable, Dict, List, Tuple

import mujoco
import mujoco.viewer
import numpy as np
import torch
import yaml


# ---------------------------------------------------------------------------
# Math — matches Isaac Lab quaternion convention (w, x, y, z)
# ---------------------------------------------------------------------------

def quat_rotate_inverse(q: np.ndarray, v: np.ndarray) -> np.ndarray:
    """Rotate world-frame vector v into body frame using body-to-world quat q."""
    qw = q[0]
    qvec = q[1:4]
    a = v * (2.0 * qw * qw - 1.0)
    b = np.cross(qvec, v) * (2.0 * qw)
    c = qvec * (2.0 * np.dot(qvec, v))
    return a - b + c


def projected_gravity_in_frame(quat: np.ndarray) -> np.ndarray:
    """Gravity unit vector rotated into the frame defined by `quat`."""
    return quat_rotate_inverse(quat, np.array([0.0, 0.0, -1.0], dtype=np.float32))


# ---------------------------------------------------------------------------
# MuJoCo helpers
# ---------------------------------------------------------------------------

TORSO_BODY_NAME = "torso_link"


def list_mujoco_joint_names(m: mujoco.MjModel) -> List[str]:
    names: List[str] = []
    for i in range(m.njnt):
        if m.jnt_type[i] == mujoco.mjtJoint.mjJNT_FREE:
            continue
        names.append(mujoco.mj_id2name(m, mujoco.mjtObj.mjOBJ_JOINT, i))
    return names


def build_joint_maps(
    isaac_joint_names: List[str],
    action_joint_names: List[str],
    mj_joint_names: List[str],
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    isaac_set = set(isaac_joint_names)
    mj_set = set(mj_joint_names)
    if isaac_set != mj_set:
        only_isaac = isaac_set - mj_set
        only_mj = mj_set - isaac_set
        raise RuntimeError(
            f"Joint name mismatch.\n"
            f"  In Isaac, not in MuJoCo: {sorted(only_isaac)}\n"
            f"  In MuJoCo, not in Isaac: {sorted(only_mj)}"
        )
    if set(action_joint_names) - isaac_set:
        raise RuntimeError(f"Action joints not in Isaac joint list: {set(action_joint_names) - isaac_set}")
    isaac_to_mj = np.array([mj_joint_names.index(n) for n in isaac_joint_names], dtype=np.int64)
    mj_to_isaac = np.array([isaac_joint_names.index(n) for n in mj_joint_names], dtype=np.int64)
    action_to_isaac = np.array([isaac_joint_names.index(n) for n in action_joint_names], dtype=np.int64)
    return isaac_to_mj, mj_to_isaac, action_to_isaac


def get_body_ang_vel_local(m: mujoco.MjModel, d: mujoco.MjData, body_id: int) -> np.ndarray:
    """Angular velocity of a body, expressed in that body's local link frame.

    Uses MuJoCo's mj_objectVelocity with flg_local=1, which is the equivalent
    of Isaac's `quat_apply_inverse(body_quat, body_link_ang_vel_w)` for the
    same body.
    """
    res = np.zeros(6, dtype=np.float64)
    mujoco.mj_objectVelocity(m, d, mujoco.mjtObj.mjOBJ_XBODY, body_id, res, 1)
    return res[:3].astype(np.float32)  # res[:3] = ang_vel, res[3:] = lin_vel


# ---------------------------------------------------------------------------
# Initial state
# ---------------------------------------------------------------------------

def set_default_pose(
    m: mujoco.MjModel,
    d: mujoco.MjData,
    q_default_isaac: np.ndarray,
    isaac_to_mj: np.ndarray,
    base_height: float | None,
) -> None:
    mujoco.mj_resetData(m, d)
    if m.nkey > 0:
        mujoco.mj_resetDataKeyframe(m, d, 0)
        if base_height is not None:
            d.qpos[2] = base_height
        print(f"[deploy] init pose: keyframe 0 loaded, base z = {d.qpos[2]:.3f}")
    else:
        d.qpos[:] = 0.0
        d.qvel[:] = 0.0
        d.qpos[2] = base_height if base_height is not None else 0.95
        d.qpos[3] = 1.0
        q_default_mj = q_default_isaac[np.argsort(isaac_to_mj)]
        d.qpos[7 : 7 + len(q_default_mj)] = q_default_mj
        print(f"[deploy] init pose: built from YAML, base z = {d.qpos[2]:.3f}")
    mujoco.mj_forward(m, d)


# ---------------------------------------------------------------------------
# Observation builder — one function per V3 obs term, exact name match
# ---------------------------------------------------------------------------
#
# Single-frame obs layout (121-d), in PolicyCfg declaration order:
#
#   [0:3]      base_ang_vel             pelvis IMU, body frame
#   [3:6]      projected_gravity        gravity in pelvis frame
#   [6:9]      projected_gravity_torso  gravity in torso_link frame
#   [9:12]     torso_ang_vel            torso_link ang vel in torso_link frame
#   [12:15]    velocity_commands        [vx, vy, wz]
#   [15:46]    joint_pos                (q - q_default), Isaac order, 31 dims
#   [46:77]    joint_vel                dq, Isaac order, 31 dims
#   [77:105]   actions                  previous action, 28 dims
#   [105:112]  left_ee_pose_command     [px py pz qw qx qy qz] in pelvis frame
#   [112:119]  right_ee_pose_command    same, right
#   [119:120]  body_height_command      scalar (m)
#   [120:121]  waist_alpha_command      scalar (alpha_t)
#
# Total: 3+3+3+3+3+31+31+28+7+7+1+1 = 121
# With history_length=5: 605-d actor input (per-term flatten, then concat).


# Terms with no per-step computation (constant commands set once per CLI run).
# Stored on the runtime state object via the closure below.

class V3ObsBuilder:
    """Builds V3 single-frame observation and maintains per-term history."""

    def __init__(
        self,
        m: mujoco.MjModel,
        d: mujoco.MjData,
        isaac_to_mj: np.ndarray,
        action_dim: int,
        n_dof_total: int,
        history_length: int,
        obs_term_order: List[str],
        single_frame_dims: Dict[str, int],
    ):
        self.m = m
        self.d = d
        self.isaac_to_mj = isaac_to_mj
        self.history_length = history_length
        self.obs_term_order = obs_term_order
        self.single_frame_dims = single_frame_dims

        # Torso link body id (cached)
        self.torso_id = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_BODY, TORSO_BODY_NAME)
        if self.torso_id < 0:
            raise RuntimeError(f"Body '{TORSO_BODY_NAME}' not found in MuJoCo model.")

        # Runtime state set by main() before each policy step.
        self.q_default_isaac: np.ndarray = np.zeros(n_dof_total, dtype=np.float32)
        self.last_action: np.ndarray = np.zeros(action_dim, dtype=np.float32)
        self.vel_cmd: np.ndarray = np.zeros(3, dtype=np.float32)
        self.left_ee_cmd: np.ndarray = np.zeros(7, dtype=np.float32)
        self.right_ee_cmd: np.ndarray = np.zeros(7, dtype=np.float32)
        self.body_height_cmd: np.ndarray = np.zeros(1, dtype=np.float32)
        self.waist_alpha_cmd: np.ndarray = np.zeros(1, dtype=np.float32)

        # Per-term history buffers — deque ordered oldest-first to match
        # IsaacLab CircularBuffer.buffer property (most recent at the END).
        self.history: Dict[str, deque] = {
            name: deque(maxlen=history_length) for name in obs_term_order
        }

        # Dispatch table for term name → compute function
        self._term_fns: Dict[str, Callable[[], np.ndarray]] = {
            "base_ang_vel": self._base_ang_vel,
            "projected_gravity": self._projected_gravity,
            "projected_gravity_torso": self._projected_gravity_torso,
            "torso_ang_vel": self._torso_ang_vel,
            "velocity_commands": self._velocity_commands,
            "joint_pos": self._joint_pos,
            "joint_vel": self._joint_vel,
            "actions": self._actions,
            "left_ee_pose_command": self._left_ee_pose_command,
            "right_ee_pose_command": self._right_ee_pose_command,
            "body_height_command": self._body_height_command,
            "waist_alpha_command": self._waist_alpha_command,
        }
        missing = [t for t in obs_term_order if t not in self._term_fns]
        if missing:
            raise RuntimeError(f"No compute function for obs terms: {missing}")

    # -- Term computers ----------------------------------------------------

    def _base_ang_vel(self) -> np.ndarray:
        # qvel[3:6] for free joint = body-frame angular velocity in MuJoCo.
        return self.d.qvel[3:6].astype(np.float32).copy()

    def _projected_gravity(self) -> np.ndarray:
        base_quat = self.d.qpos[3:7].astype(np.float32)
        return projected_gravity_in_frame(base_quat)

    def _projected_gravity_torso(self) -> np.ndarray:
        # d.xquat[body_id] = body-to-world quaternion (w, x, y, z)
        torso_quat = self.d.xquat[self.torso_id].astype(np.float32)
        return projected_gravity_in_frame(torso_quat)

    def _torso_ang_vel(self) -> np.ndarray:
        return get_body_ang_vel_local(self.m, self.d, self.torso_id)

    def _velocity_commands(self) -> np.ndarray:
        return self.vel_cmd

    def _joint_pos(self) -> np.ndarray:
        # joint_pos_rel = q - q_default, Isaac joint order
        q_mj = self.d.qpos[7:].astype(np.float32)
        q_isaac = q_mj[self.isaac_to_mj]
        return q_isaac - self.q_default_isaac

    def _joint_vel(self) -> np.ndarray:
        dq_mj = self.d.qvel[6:].astype(np.float32)
        return dq_mj[self.isaac_to_mj]

    def _actions(self) -> np.ndarray:
        return self.last_action

    def _left_ee_pose_command(self) -> np.ndarray:
        return self.left_ee_cmd

    def _right_ee_pose_command(self) -> np.ndarray:
        return self.right_ee_cmd

    def _body_height_command(self) -> np.ndarray:
        return self.body_height_cmd

    def _waist_alpha_command(self) -> np.ndarray:
        return self.waist_alpha_cmd

    # -- History assembly --------------------------------------------------

    def reset_history(self) -> None:
        """Clear all per-term history buffers."""
        for q in self.history.values():
            q.clear()

    def step(self) -> np.ndarray:
        """Compute current frame for each term, push to history, return flat obs."""
        per_term_flat: List[np.ndarray] = []
        for term_name in self.obs_term_order:
            current = self._term_fns[term_name]().astype(np.float32)
            expected = self.single_frame_dims[term_name]
            if current.shape != (expected,):
                raise RuntimeError(
                    f"Term '{term_name}' produced shape {current.shape}, expected ({expected},)"
                )
            buf = self.history[term_name]
            buf.append(current)
            # Pad with the first real frame at startup so the buffer is always
            # full — matches IsaacLab CircularBuffer behaviour (first push fills
            # all empty slots, see circular_buffer.py:137-141).
            while len(buf) < self.history_length:
                buf.append(current)
            # Flatten oldest → newest (deque is already in that order).
            per_term_flat.append(np.concatenate(list(buf), axis=0))
        return np.concatenate(per_term_flat, axis=0).astype(np.float32)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Deploy HV1 V3 loco-manip policy in MuJoCo.")
    parser.add_argument("--config", type=str, required=True, help="Path to mujoco_config.yaml (V3).")
    parser.add_argument("--policy", type=str, default=None, help="Override policy.pt path.")
    parser.add_argument("--xml", type=str, default=None, help="Override MJCF path.")
    parser.add_argument("--duration", type=float, default=120.0)
    parser.add_argument("--base_height", type=float, default=None)
    parser.add_argument("--realtime", action="store_true", default=True)
    # base velocity command
    parser.add_argument("--cmd_lin_x", type=float, default=0.0)
    parser.add_argument("--cmd_lin_y", type=float, default=0.0)
    parser.add_argument("--cmd_ang_z", type=float, default=0.0)
    # EE pose commands (pelvis frame)
    parser.add_argument(
        "--left_ee", nargs=7, type=float,
        default=[0.30, 0.26, 0.24, 1.0, 0.0, 0.0, 0.0],
        help="Left EE: px py pz qw qx qy qz (pelvis frame)",
    )
    parser.add_argument(
        "--right_ee", nargs=7, type=float,
        default=[0.30, -0.26, 0.24, 1.0, 0.0, 0.0, 0.0],
        help="Right EE: px py pz qw qx qy qz (pelvis frame)",
    )
    # V3-only scalar commands
    parser.add_argument(
        "--cmd_body_height", type=float, default=0.90,
        help="Target body (pelvis) height in metres. Training range [0.85, 0.95].",
    )
    parser.add_argument(
        "--cmd_waist_alpha", type=float, default=1.0,
        help="Waist regularization alpha_t. Training range [0.1, 3.0]; "
             "1.0 ≈ nominal waist stiffness.",
    )
    # Obs structure overrides (only needed if YAML doesn't match defaults)
    parser.add_argument(
        "--history_length", type=int, default=5,
        help="History buffer length per obs term. Must match training value.",
    )
    args = parser.parse_args()

    # ---- Load config ------------------------------------------------------
    with open(args.config, "r") as f:
        cfg = yaml.safe_load(f)

    xml_path = args.xml or cfg["robot"]["xml_path"]
    policy_path = args.policy or cfg["policy"]["jit_path"]
    sim_dt = float(cfg["control"]["sim_dt"])
    decimation = int(cfg["control"]["decimation"])
    joint_names_isaac = cfg["robot"]["joint_names_isaac_order"]
    joint_names_action = cfg["action"]["joint_names_action_order"]
    q_default_isaac = np.array(cfg["robot"]["default_joint_pos"], dtype=np.float32)
    kp_isaac = np.array(cfg["robot"]["kp"], dtype=np.float32)
    kd_isaac = np.array(cfg["robot"]["kd"], dtype=np.float32)
    action_scale = float(cfg["action"]["scale"])
    use_default_offset = bool(cfg["action"]["use_default_offset"])
    n_dof = int(cfg["robot"]["num_dof_total"])
    action_dim = int(cfg["action"]["dim"])
    total_obs_dim_yaml = int(cfg["observation"]["total_dim"])
    obs_terms_yaml = cfg["observation"]["terms"]  # list of {name, dim}; dim is post-history-flatten

    # Build single-frame dim table by dividing YAML per-term dim by history_length.
    # (dump_mujoco_config reports flattened dim; we want single frame for buffer
    # bookkeeping.)
    history_length = args.history_length
    single_frame_dims: Dict[str, int] = {}
    obs_term_order: List[str] = []
    for entry in obs_terms_yaml:
        name = entry["name"]
        dim_total = int(entry["dim"])
        if dim_total % history_length != 0:
            raise RuntimeError(
                f"Term '{name}' YAML dim {dim_total} not divisible by history "
                f"length {history_length}. Was training history_length different?"
            )
        single_frame_dims[name] = dim_total // history_length
        obs_term_order.append(name)

    single_frame_total = sum(single_frame_dims.values())
    if single_frame_total * history_length != total_obs_dim_yaml:
        raise RuntimeError(
            f"YAML total obs {total_obs_dim_yaml} != sum(per-term × history) "
            f"{single_frame_total * history_length}. Obs structure mismatch."
        )

    print(f"[deploy] config            : {args.config}")
    print(f"[deploy] xml               : {xml_path}")
    print(f"[deploy] policy            : {policy_path}")
    print(f"[deploy] sim_dt            : {sim_dt}  decimation={decimation}  policy_dt={sim_dt * decimation}")
    print(f"[deploy] n_dof_total       : {n_dof}    action_dim={action_dim}")
    print(f"[deploy] action_scale      : {action_scale}    use_default_offset={use_default_offset}")
    print(f"[deploy] history_length    : {history_length}")
    print(f"[deploy] single_frame_dim  : {single_frame_total}")
    print(f"[deploy] total_obs_dim     : {total_obs_dim_yaml}  (from YAML)")
    print(f"[deploy] obs term order    :")
    for name in obs_term_order:
        print(f"             {name:<30s} single={single_frame_dims[name]:>3d}  history={single_frame_dims[name] * history_length:>3d}")

    # ---- Load MuJoCo model -----------------------------------------------
    m = mujoco.MjModel.from_xml_path(xml_path)
    d = mujoco.MjData(m)
    m.opt.timestep = sim_dt

    mj_joint_names = list_mujoco_joint_names(m)
    assert len(mj_joint_names) == n_dof, (
        f"MuJoCo has {len(mj_joint_names)} hinge/slide joints, YAML says {n_dof}."
    )

    isaac_to_mj, mj_to_isaac, action_to_isaac = build_joint_maps(
        joint_names_isaac, joint_names_action, mj_joint_names
    )
    print("[deploy] joint maps built — Isaac/MuJoCo joint sets match.")

    kp_mj = kp_isaac[mj_to_isaac]
    kd_mj = kd_isaac[mj_to_isaac]
    q_default_mj = q_default_isaac[mj_to_isaac]

    # Per-joint torque limits from actuator ctrlrange (NaN guard).
    tau_limit_mj = np.zeros(n_dof, dtype=np.float32)
    for j_mj, name in enumerate(mj_joint_names):
        for a in range(m.nu):
            if m.actuator_trnid[a, 0] == mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_JOINT, name):
                lo, hi = m.actuator_ctrlrange[a]
                tau_limit_mj[j_mj] = max(abs(lo), abs(hi))
                break
        else:
            tau_limit_mj[j_mj] = 1e6
    print(f"[deploy] torque clamps     : min={tau_limit_mj.min():.1f}  max={tau_limit_mj.max():.1f} Nm")

    # ---- Load policy -----------------------------------------------------
    policy = torch.jit.load(policy_path, map_location="cpu").eval()
    n_params = sum(p.numel() for p in policy.parameters())
    print(f"[deploy] policy loaded ({n_params:,} params)")

    # ---- Initial state ---------------------------------------------------
    set_default_pose(m, d, q_default_isaac, isaac_to_mj, args.base_height)

    lowest_z = float("inf")
    for g in range(m.ngeom):
        if m.geom_bodyid[g] == 0:
            continue
        lowest_z = min(lowest_z, float(d.geom_xpos[g, 2]))
    print(f"[deploy] init lowest geom z = {lowest_z:.4f}  (negative ⇒ ground penetration)")

    # ---- Build obs builder ----------------------------------------------
    obs_builder = V3ObsBuilder(
        m=m, d=d,
        isaac_to_mj=isaac_to_mj,
        action_dim=action_dim,
        n_dof_total=n_dof,
        history_length=history_length,
        obs_term_order=obs_term_order,
        single_frame_dims=single_frame_dims,
    )
    obs_builder.q_default_isaac = q_default_isaac.copy()
    obs_builder.vel_cmd = np.array([args.cmd_lin_x, args.cmd_lin_y, args.cmd_ang_z], dtype=np.float32)
    obs_builder.left_ee_cmd = np.array(args.left_ee, dtype=np.float32)
    obs_builder.right_ee_cmd = np.array(args.right_ee, dtype=np.float32)
    obs_builder.body_height_cmd = np.array([args.cmd_body_height], dtype=np.float32)
    obs_builder.waist_alpha_cmd = np.array([args.cmd_waist_alpha], dtype=np.float32)

    print(f"[deploy] cmd_velocity      : {obs_builder.vel_cmd.tolist()}")
    print(f"[deploy] left_ee_cmd       : {obs_builder.left_ee_cmd.tolist()}")
    print(f"[deploy] right_ee_cmd      : {obs_builder.right_ee_cmd.tolist()}")
    print(f"[deploy] cmd_body_height   : {args.cmd_body_height}")
    print(f"[deploy] cmd_waist_alpha   : {args.cmd_waist_alpha}")
    print(f"[deploy] torso_link body_id: {obs_builder.torso_id}")
    print(f"[deploy] starting viewer …")

    # Verify obs dimension on first call.
    first_obs = obs_builder.step()
    if first_obs.shape[0] != total_obs_dim_yaml:
        raise RuntimeError(
            f"First obs dim {first_obs.shape[0]} != expected {total_obs_dim_yaml}. "
            f"Check obs term order or single-frame dims."
        )
    print(f"[deploy] first obs dim     : {first_obs.shape[0]} ✓")
    # Reset history so the first true step doesn't reuse the warmup frame.
    obs_builder.reset_history()

    # ---- Control loop ---------------------------------------------------
    target_dof_pos_mj = q_default_mj.copy()
    counter = 0

    with mujoco.viewer.launch_passive(m, d) as viewer:
        start = time.time()
        while viewer.is_running() and time.time() - start < args.duration:
            step_start = time.time()

            # PD control every physics step
            q_mj = d.qpos[7:]
            dq_mj = d.qvel[6:]
            tau = kp_mj * (target_dof_pos_mj - q_mj) - kd_mj * dq_mj
            tau = np.clip(tau, -tau_limit_mj, tau_limit_mj)
            d.qfrc_applied[6:] = tau

            mujoco.mj_step(m, d)
            counter += 1

            # NaN guard
            if not np.all(np.isfinite(d.qpos)):
                print(f"[deploy] !! qpos went NaN at step {counter} — stopping.")
                print(f"[deploy]    base z just before NaN: {d.qpos[2]:.4f}")
                print(f"[deploy]    last tau abs max: {np.abs(tau).max():.2f}")
                break

            # Policy every `decimation` steps
            if counter % decimation == 0:
                obs = obs_builder.step()
                with torch.no_grad():
                    obs_t = torch.from_numpy(obs).unsqueeze(0)
                    action_t = policy(obs_t)
                action = action_t.detach().numpy().squeeze(0).astype(np.float32)
                obs_builder.last_action = action.copy()

                # Build PD target in Isaac order: default everywhere, override
                # the action_dim joints with default + scale * action.
                target_dof_pos_isaac = q_default_isaac.copy()
                if use_default_offset:
                    target_dof_pos_isaac[action_to_isaac] = (
                        q_default_isaac[action_to_isaac] + action_scale * action
                    )
                else:
                    target_dof_pos_isaac[action_to_isaac] = action_scale * action
                target_dof_pos_mj = target_dof_pos_isaac[mj_to_isaac]

                # Heartbeat — every ~1s at 50 Hz policy
                policy_steps = counter // decimation
                if policy_steps % 50 == 1:
                    print(
                        f"[deploy] t={d.time:6.2f}s  base_z={d.qpos[2]:.3f}  "
                        f"|action|={np.abs(action).max():.2f}  |tau|={np.abs(tau).max():.1f}"
                    )

            viewer.sync()

            if args.realtime:
                slack = sim_dt - (time.time() - step_start)
                if slack > 0:
                    time.sleep(slack)

    print(f"[deploy] simulation ended after {time.time() - start:.1f}s, {counter} physics steps")


if __name__ == "__main__":
    sys.exit(main())
